nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@types/testing-library__react@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  graphql-config@*:
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  recharts@*:
    peerDependencies:
      prop-types: "*"
  web-agoric@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-akash@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-assetmantle@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-band@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-bitsong@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-comdex@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-cosmos@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-crescent@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-desmos@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-elrond@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql: "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-emoney@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-evmos@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-flow@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-likecoin@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-nomic@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-nym@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-osmosis@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-persistence@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-provenance@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-regen@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-rizon@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-shentu@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-sifchain@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-solana@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"
  web-stride@*:
    peerDependencies:
      "@babel/core": "*"
      "@types/jest": "*"
      graphql-tag: "*"
      prop-types: "*"
      react: "*"
      react-dom: "*"
      subscriptions-transport-ws: "*"
      webpack: "*"
      ws: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
