name: Test
on:
  pull_request:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install modules
      run: corepack enable && yarn
    - name: Run lint check
      run: yarn lint

  Unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install modules
      run: corepack enable && yarn
    - name: Run tests
      run: yarn test --coverage

  Build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install modules
      run: corepack enable && yarn
    - name: Run build check
      run: yarn build
